// ? Names
export const firstNameAutocomplete = "given-name";
export const middleNameAutocomplete = "additional-name";
export const lastNameAutocomplete = "family-name";
export const fullNameAutocomplete = "name";

// ? Misc Login
export const emailAutocomplete = "email";
export const usernameAutocomplete = "username";
export const newPasswordAutocomplete = "new-password";
export const currentPasswordAutocomplete = "current-password";
export const oneTimeCodeAutocomplete = "one-time-code";

// ? Organization
export const organizationAutocomplete = "organization";
export const organizationalTitleAutocomplete = "organization-title";

// ? Address
/* 
    ! addressLevel2: City
    ! addressLevel1: State
    ! country: A country or territory code
    ! countryName: A country or territory name
*/
export const streetAddressAutocomplete = "street-address";
export const shippingAddressAutocomplete = "shipping";
export const billingAddressAutocomplete = "billing";
export const addressLevel4Autocomplete = "address-level4";
export const addressLevel3Autocomplete = "address-level3";
export const addressLevel2Autocomplete = "address-level2";
export const addressLevel1Autocomplete = "address-level1";
export const countryAutocomplete = "country";
export const countryNameAutocomplete = "country-name";
export const postalCodeAutocomplete = "postal-code";

// ? Credit Card
/* 
    ! creditCardExpiration: full expiration date in "MM/YY" or "MM/YYYY"
    ! creditCardExpirationMonth: month of expiration only
    ! creditCardExpirationYear: year of expiration only
    ! creditCardType: Visa or Master Card, etc.
*/
export const firstNameCreditCardAutocomplete = "cc-given-name";
export const middleNameCreditCardAutocomplete = "cc-additional-name";
export const lastNameCreditCardAutocomplete = "cc-family-name";
export const fullNameCreditCardAutocomplete = "cc-name";
export const creditCardNumberAutocomplete = "cc-number";
export const creditCardExpirationAutocomplete = "cc-exp";
export const creditCardExpirationMonthAutocomplete = "cc-exp-month";
export const creditCardExpirationYearAutocomplete = "cc-exp-year";
export const creditCardSecurityCodeAutocomplete = "cc-csc";
export const creditCardTypeAutocomplete = "cc-type";

// ? Birth Date
/* 
    ! birthday: Full birth date
    ! all others: separated by month, date, or year
*/
export const birthdayAutocomplete = "bday";
export const birthdayDayAutocomplete = "bday-day";
export const birthdayMonthAutocomplete = "bday-month";
export const birthdayYearAutocomplete = "bday-year";

// ? Phone Number
/* 
    ! phoneNumber: Full phone number with country code included
    ! countryCode: The country code, such as "1" for the United States
    ! phoneNumberNational: The phone number without the country code
    ! phoneExtension: A code within the phone number, such as an office extension in a company
*/
export const phoneNumberAutocomplete = "tel";
export const countryCodeAutocomplete = "tel-country-code";
export const phoneNumberNationalAutocomplete = "tel-national";
export const phoneExtensionAutocomplete = "tel-extension";

// ? Misc
/* 
    ! sex: Biological sex (Male or Female)
    ! impp: A URL for an instant messaging protocol endpoint, such as "xmpp:username@example.net"
    ! url: A URL, such as a home page or company website address as appropriate given the context of the other fields in the form.
    ! photo: The URL of an image representing the person, company, or contact information given in the other fields in the form.
    ! webAuthn: Passkeys generated by the Web Authentication API
*/
export const sexAutocomplete = "sex";
export const imppAutocomplete = "impp";
export const urlAutocomplete = "url";
export const photoAutocomplete = "photo";
export const webAuthnAutocomplete = "webauthn";