export const phoneNumberCountryCodes = [
  { country: "Afghanistan", code: "+93", abbreviation: "AF" },
  { country: "Albania", code: "+355", abbreviation: "AL" },
  { country: "Algeria", code: "+213", abbreviation: "DZ" },
  { country: "American Samoa", code: "+1-684", abbreviation: "AS" },
  { country: "Andorra", code: "+376", abbreviation: "AD" },
  { country: "Angola", code: "+244", abbreviation: "AO" },
  { country: "Anguilla", code: "+1-264", abbreviation: "AI" },
  { country: "Antarctica", code: "+672", abbreviation: "AQ" },
  { country: "Antigua and Barbuda", code: "+1-268", abbreviation: "AG" },
  { country: "Argentina", code: "+54", abbreviation: "AR" },
  { country: "Armenia", code: "+374", abbreviation: "AM" },
  { country: "Aruba", code: "+297", abbreviation: "AW" },
  { country: "Australia", code: "+61", abbreviation: "AU" },
  { country: "Austria", code: "+43", abbreviation: "AT" },
  { country: "Azerbaijan", code: "+994", abbreviation: "AZ" },
  { country: "Bahamas", code: "+1-242", abbreviation: "BS" },
  { country: "Bahrain", code: "+973", abbreviation: "BH" },
  { country: "Bangladesh", code: "+880", abbreviation: "BD" },
  { country: "Barbados", code: "+1-246", abbreviation: "BB" },
  { country: "Belarus", code: "+375", abbreviation: "BY" },
  { country: "Belgium", code: "+32", abbreviation: "BE" },
  { country: "Belize", code: "+501", abbreviation: "BZ" },
  { country: "Benin", code: "+229", abbreviation: "BJ" },
  { country: "Bermuda", code: "+1-441", abbreviation: "BM" },
  { country: "Bhutan", code: "+975", abbreviation: "BT" },
  { country: "Bolivia", code: "+591", abbreviation: "BO" },
  { country: "Bosnia and Herzegovina", code: "+387", abbreviation: "BA" },
  { country: "Botswana", code: "+267", abbreviation: "BW" },
  { country: "Brazil", code: "+55", abbreviation: "BR" },
  {
    country: "British Indian Ocean Territory",
    code: "+246",
    abbreviation: "IO",
  },
  { country: "British Virgin Islands", code: "+1-284", abbreviation: "VG" },
  { country: "Brunei", code: "+673", abbreviation: "BN" },
  { country: "Bulgaria", code: "+359", abbreviation: "BG" },
  { country: "Burkina Faso", code: "+226", abbreviation: "BF" },
  { country: "Burundi", code: "+257", abbreviation: "BI" },
  { country: "Cambodia", code: "+855", abbreviation: "KH" },
  { country: "Cameroon", code: "+237", abbreviation: "CM" },
  { country: "Canada", code: "+1", abbreviation: "CA" },
  { country: "Cape Verde", code: "+238", abbreviation: "CV" },
  { country: "Cayman Islands", code: "+1-345", abbreviation: "KY" },
  { country: "Central African Republic", code: "+236", abbreviation: "CF" },
  { country: "Chad", code: "+235", abbreviation: "TD" },
  { country: "Chile", code: "+56", abbreviation: "CL" },
  { country: "China", code: "+86", abbreviation: "CN" },
  { country: "Christmas Island", code: "+61", abbreviation: "CX" },
  { country: "Cocos Islands", code: "+61", abbreviation: "CC" },
  { country: "Colombia", code: "+57", abbreviation: "CO" },
  { country: "Comoros", code: "+269", abbreviation: "KM" },
  { country: "Cook Islands", code: "+682", abbreviation: "CK" },
  { country: "Costa Rica", code: "+506", abbreviation: "CR" },
  { country: "Croatia", code: "+385", abbreviation: "HR" },
  { country: "Cuba", code: "+53", abbreviation: "CU" },
  { country: "Curacao", code: "+599", abbreviation: "CW" },
  { country: "Cyprus", code: "+357", abbreviation: "CY" },
  { country: "Czech Republic", code: "+420", abbreviation: "CZ" },
  {
    country: "Democratic Republic of the Congo",
    code: "+243",
    abbreviation: "CD",
  },
  { country: "Denmark", code: "+45", abbreviation: "DK" },
  { country: "Djibouti", code: "+253", abbreviation: "DJ" },
  { country: "Dominica", code: "+1-767", abbreviation: "DM" },
  {
    country: "Dominican Republic",
    code: "+1-809, 1-829, 1-849",
    abbreviation: "DO",
  },
  { country: "East Timor", code: "+670", abbreviation: "TL" },
  { country: "Ecuador", code: "+593", abbreviation: "EC" },
  { country: "Egypt", code: "+20", abbreviation: "EG" },
  { country: "El Salvador", code: "+503", abbreviation: "SV" },
  { country: "Equatorial Guinea", code: "+240", abbreviation: "GQ" },
  { country: "Eritrea", code: "+291", abbreviation: "ER" },
  { country: "Estonia", code: "+372", abbreviation: "EE" },
  { country: "Ethiopia", code: "+251", abbreviation: "ET" },
  { country: "Falkland Islands", code: "+500", abbreviation: "FK" },
  { country: "Faroe Islands", code: "+298", abbreviation: "FO" },
  { country: "Fiji", code: "+679", abbreviation: "FJ" },
  { country: "Finland", code: "+358", abbreviation: "FI" },
  { country: "France", code: "+33", abbreviation: "FR" },
  { country: "French Polynesia", code: "+689", abbreviation: "PF" },
  { country: "Gabon", code: "+241", abbreviation: "GA" },
  { country: "Gambia", code: "+220", abbreviation: "GM" },
  { country: "Georgia", code: "+995", abbreviation: "GE" },
  { country: "Germany", code: "+49", abbreviation: "DE" },
  { country: "Ghana", code: "+233", abbreviation: "GH" },
  { country: "Gibraltar", code: "+350", abbreviation: "GI" },
  { country: "Greece", code: "+30", abbreviation: "GR" },
  { country: "Greenland", code: "+299", abbreviation: "GL" },
  { country: "Grenada", code: "+1-473", abbreviation: "GD" },
  { country: "Guam", code: "+1-671", abbreviation: "GU" },
  { country: "Guatemala", code: "+502", abbreviation: "GT" },
  { country: "Guernsey", code: "+44-1481", abbreviation: "GG" },
  { country: "Guinea", code: "+224", abbreviation: "GN" },
  { country: "Guinea-Bissau", code: "+245", abbreviation: "GW" },
  { country: "Guyana", code: "+592", abbreviation: "GY" },
  { country: "Haiti", code: "+509", abbreviation: "HT" },
  { country: "Honduras", code: "+504", abbreviation: "HN" },
  { country: "Hong Kong", code: "+852", abbreviation: "HK" },
  { country: "Hungary", code: "+36", abbreviation: "HU" },
  { country: "Iceland", code: "+354", abbreviation: "IS" },
  { country: "India", code: "+91", abbreviation: "IN" },
  { country: "Indonesia", code: "+62", abbreviation: "ID" },
  { country: "Iran", code: "+98", abbreviation: "IR" },
  { country: "Iraq", code: "+964", abbreviation: "IQ" },
  { country: "Ireland", code: "+353", abbreviation: "IE" },
  { country: "Isle of Man", code: "+44-1624", abbreviation: "IM" },
  { country: "Israel", code: "+972", abbreviation: "IL" },
  { country: "Italy", code: "+39", abbreviation: "IT" },
  { country: "Ivory Coast", code: "+225", abbreviation: "CI" },
  { country: "Jamaica", code: "+1-876", abbreviation: "JM" },
  { country: "Japan", code: "+81", abbreviation: "JP" },
  { country: "Jersey", code: "+44-1534", abbreviation: "JE" },
  { country: "Jordan", code: "+962", abbreviation: "JO" },
  { country: "Kazakhstan", code: "+7", abbreviation: "KZ" },
  { country: "Kenya", code: "+254", abbreviation: "KE" },
  { country: "Kiribati", code: "+686", abbreviation: "KI" },
  { country: "Kuwait", code: "+965", abbreviation: "KW" },
  { country: "Kyrgyzstan", code: "+996", abbreviation: "KG" },
  { country: "Laos", code: "+856", abbreviation: "LA" },
  { country: "Latvia", code: "+371", abbreviation: "LV" },
  { country: "Lebanon", code: "+961", abbreviation: "LB" },
  { country: "Lesotho", code: "+266", abbreviation: "LS" },
  { country: "Liberia", code: "+231", abbreviation: "LR" },
  { country: "Libya", code: "+218", abbreviation: "LY" },
  { country: "Liechtenstein", code: "+423", abbreviation: "LI" },
  { country: "Lithuania", code: "+370", abbreviation: "LT" },
  { country: "Luxembourg", code: "+352", abbreviation: "LU" },
  { country: "Macao", code: "+853", abbreviation: "MO" },
  { country: "Macedonia", code: "+389", abbreviation: "MK" },
  { country: "Madagascar", code: "+261", abbreviation: "MG" },
  { country: "Malawi", code: "+265", abbreviation: "MW" },
  { country: "Malaysia", code: "+60", abbreviation: "MY" },
  { country: "Maldives", code: "+960", abbreviation: "MV" },
  { country: "Mali", code: "+223", abbreviation: "ML" },
  { country: "Malta", code: "+356", abbreviation: "MT" },
  { country: "Marshall Islands", code: "+692", abbreviation: "MH" },
  { country: "Mauritania", code: "+222", abbreviation: "MR" },
  { country: "Mauritius", code: "+230", abbreviation: "MU" },
  { country: "Mayotte", code: "+262", abbreviation: "YT" },
  { country: "Mexico", code: "+52", abbreviation: "MX" },
  { country: "Micronesia", code: "+691", abbreviation: "FM" },
  { country: "Moldova", code: "+373", abbreviation: "MD" },
  { country: "Monaco", code: "+377", abbreviation: "MC" },
  { country: "Mongolia", code: "+976", abbreviation: "MN" },
  { country: "Montenegro", code: "+382", abbreviation: "ME" },
  { country: "Montserrat", code: "+1-664", abbreviation: "MS" },
  { country: "Morocco", code: "+212", abbreviation: "MA" },
  { country: "Mozambique", code: "+258", abbreviation: "MZ" },
  { country: "Myanmar", code: "+95", abbreviation: "MM" },
  { country: "Namibia", code: "+264", abbreviation: "NA" },
  { country: "Nauru", code: "+674", abbreviation: "NR" },
  { country: "Nepal", code: "+977", abbreviation: "NP" },
  { country: "Netherlands", code: "+31", abbreviation: "NL" },
  { country: "New Caledonia", code: "+687", abbreviation: "NC" },
  { country: "New Zealand", code: "+64", abbreviation: "NZ" },
  { country: "Nicaragua", code: "+505", abbreviation: "NI" },
  { country: "Niger", code: "+227", abbreviation: "NE" },
  { country: "Nigeria", code: "+234", abbreviation: "NG" },
  { country: "Niue", code: "+683", abbreviation: "NU" },
  { country: "North Korea", code: "+850", abbreviation: "KP" },
  { country: "Northern Mariana Islands", code: "+1-670", abbreviation: "MP" },
  { country: "Norway", code: "+47", abbreviation: "NO" },
  { country: "Oman", code: "+968", abbreviation: "OM" },
  { country: "Pakistan", code: "+92", abbreviation: "PK" },
  { country: "Palau", code: "+680", abbreviation: "PW" },
  { country: "Palestine", code: "+970", abbreviation: "PS" },
  { country: "Panama", code: "+507", abbreviation: "PA" },
  { country: "Papua New Guinea", code: "+675", abbreviation: "PG" },
  { country: "Paraguay", code: "+595", abbreviation: "PY" },
  { country: "Peru", code: "+51", abbreviation: "PE" },
  { country: "Philippines", code: "+63", abbreviation: "PH" },
  { country: "Pitcairn", code: "+64", abbreviation: "PN" },
  { country: "Poland", code: "+48", abbreviation: "PL" },
  { country: "Portugal", code: "+351", abbreviation: "PT" },
  { country: "Puerto Rico", code: "+1-787, 1-939", abbreviation: "PR" },
  { country: "Qatar", code: "+974", abbreviation: "QA" },
  { country: "Republic of the Congo", code: "+242", abbreviation: "CG" },
  { country: "Reunion", code: "+262", abbreviation: "RE" },
  { country: "Romania", code: "+40", abbreviation: "RO" },
  { country: "Russia", code: "+7", abbreviation: "RU" },
  { country: "Rwanda", code: "+250", abbreviation: "RW" },
  { country: "Saint Barthelemy", code: "+590", abbreviation: "BL" },
  { country: "Saint Helena", code: "+290", abbreviation: "SH" },
  { country: "Saint Kitts and Nevis", code: "+1-869", abbreviation: "KN" },
  { country: "Saint Lucia", code: "+1-758", abbreviation: "LC" },
  { country: "Saint Martin", code: "+590", abbreviation: "MF" },
  { country: "Saint Pierre and Miquelon", code: "+508", abbreviation: "PM" },
  {
    country: "Saint Vincent and the Grenadines",
    code: "+1-784",
    abbreviation: "VC",
  },
  { country: "Samoa", code: "+685", abbreviation: "WS" },
  { country: "San Marino", code: "+378", abbreviation: "SM" },
  { country: "Sao Tome and Principe", code: "+239", abbreviation: "ST" },
  { country: "Saudi Arabia", code: "+966", abbreviation: "SA" },
  { country: "Senegal", code: "+221", abbreviation: "SN" },
  { country: "Serbia", code: "+381", abbreviation: "RS" },
  { country: "Seychelles", code: "+248", abbreviation: "SC" },
  { country: "Sierra Leone", code: "+232", abbreviation: "SL" },
  { country: "Singapore", code: "+65", abbreviation: "SG" },
  { country: "Sint Maarten", code: "+1-721", abbreviation: "SX" },
  { country: "Slovakia", code: "+421", abbreviation: "SK" },
  { country: "Slovenia", code: "+386", abbreviation: "SI" },
  { country: "Solomon Islands", code: "+677", abbreviation: "SB" },
  { country: "Somalia", code: "+252", abbreviation: "SO" },
  { country: "South Africa", code: "+27", abbreviation: "ZA" },
  { country: "South Korea", code: "+82", abbreviation: "KR" },
  { country: "South Sudan", code: "+211", abbreviation: "SS" },
  { country: "Spain", code: "+34", abbreviation: "ES" },
  { country: "Sri Lanka", code: "+94", abbreviation: "LK" },
  { country: "Sudan", code: "+249", abbreviation: "SD" },
  { country: "Suriname", code: "+597", abbreviation: "SR" },
  { country: "Svalbard and Jan Mayen", code: "+47", abbreviation: "SJ" },
  { country: "Swaziland", code: "+268", abbreviation: "SZ" },
  { country: "Sweden", code: "+46", abbreviation: "SE" },
  { country: "Switzerland", code: "+41", abbreviation: "CH" },
  { country: "Syria", code: "+963", abbreviation: "SY" },
  { country: "Taiwan", code: "+886", abbreviation: "TW" },
  { country: "Tajikistan", code: "+992", abbreviation: "TJ" },
  { country: "Tanzania", code: "+255", abbreviation: "TZ" },
  { country: "Thailand", code: "+66", abbreviation: "TH" },
  { country: "Togo", code: "+228", abbreviation: "TG" },
  { country: "Tokelau", code: "+690", abbreviation: "TK" },
  { country: "Tonga", code: "+676", abbreviation: "TO" },
  { country: "Trinidad and Tobago", code: "+1-868", abbreviation: "TT" },
  { country: "Tunisia", code: "+216", abbreviation: "TN" },
  { country: "Turkey", code: "+90", abbreviation: "TR" },
  { country: "Turkmenistan", code: "+993", abbreviation: "TM" },
  { country: "Turks and Caicos Islands", code: "+1-649", abbreviation: "TC" },
  { country: "Tuvalu", code: "+688", abbreviation: "TV" },
  { country: "U.S. Virgin Islands", code: "+1-340", abbreviation: "VI" },
  { country: "Uganda", code: "+256", abbreviation: "UG" },
  { country: "Ukraine", code: "+380", abbreviation: "UA" },
  { country: "United Arab Emirates", code: "+971", abbreviation: "AE" },
  { country: "United Kingdom", code: "+44", abbreviation: "GB" },
  { country: "United States", code: "+1", abbreviation: "US" },
  { country: "Uruguay", code: "+598", abbreviation: "UY" },
  { country: "Uzbekistan", code: "+998", abbreviation: "UZ" },
  { country: "Vanuatu", code: "+678", abbreviation: "VU" },
  { country: "Vatican", code: "+379", abbreviation: "VA" },
  { country: "Venezuela", code: "+58", abbreviation: "VE" },
  { country: "Vietnam", code: "+84", abbreviation: "VN" },
  { country: "Wallis and Futuna", code: "+681", abbreviation: "WF" },
  { country: "Western Sahara", code: "+212", abbreviation: "EH" },
  { country: "Yemen", code: "+967", abbreviation: "YE" },
  { country: "Zambia", code: "+260", abbreviation: "ZM" },
  { country: "Zimbabwe", code: "+263", abbreviation: "ZW" },
];
